apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturaya-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facturaya-app
  template:
    metadata:
      labels:
        app: facturaya-app
    spec:
      containers:
        - name: app
          image: localhost/facturaya-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: facturaya-app-config
            - secretRef:
                name: facturaya-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: facturaya-app
spec:
  type: NodePort
  selector:
    app: facturaya-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: facturaya-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: facturaya-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: facturaya-app-config
data:
  HOST_DB: facturaya-db
  PORT_DB: "5432"
  POSTGRES_DB: facturaya
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: facturaya-app-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cm9vdA==